### ISSUE TITLE
MM generates extra "MaxItems" and "MiniItems"

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/magic-module-specs#107]
"route_table": {
                Type: schema.TypeList,
                Computed: true,
                Elem: &schema.Resource{
                    Schema: map[string]*schema.Schema{
                        "routes": {
                            Type: schema.TypeList,
                            Computed: true,
                            MinItems: ,
                            MaxItems: ,
                            Elem: &schema.Resource{
                                Schema: map[string]*schema.Schema{
                                    "address_prefixes": {
                                        Type: schema.TypeList,
                                        Computed: true,
                                        MinItems: ,
                                        MaxItems: ,
                                        Elem: &schema.Schema{
                                            Type: schema.TypeString,
                                        },
                                    },
                                    "next_hop_ip_address": {
                                        Type: schema.TypeString,
                                        Computed: true,
                                    },
                                },
                            },
                        },
                    },
                },
            },

**Comment by houkms** [comment]
It's a problem in Magic-Modules and it was solved in [MM-PR-18](https://github.com/VSChina/magic-modules/pull/18)
