### ISSUE TITLE
Default versions of teraform.yaml and ansible.yaml

### ISSUE THREAD

**Issue by zikalino** [Azure/magic-module-specs#14]
Currently MM needs these files in order to generate something, so it's impossible to attempt fully automatic code generation.
I think these could be also generated automatically (if don't exist yet).
any suggestions?

**Comment by zikalino** [comment]
@metacpp @JunyiYi 

Just need to decide whether I should generate:
ansible.yaml
terraform.yaml

or:

ansible.yaml.template
terraform.yaml.template

First approach may be tricky, because I will have to make sure I don’t overwrite manually changed files.

Pls let me know what do you prefer, I don’t know if “.template” approach is going to be convenient.
Perhaps I should do the first one and be selective when creating PR….

Any other ideas?

**Comment by JunyiYi** [comment]
Copied from internal email thread:

> By @metacpp : The 1st one should be enough.

> By @zikalino : Yes, I think so. If you need to existing one to get updated, you will need to delete old version from the repo.
I guess that should work, unless we’ll have to change structure too frequently.

> By @jeffreyCline : Yes, the first one should be enough for now, but is not sustainable long term… for now I think it is fine though.

**Comment by JunyiYi** [comment]
@zikalino You mentioned "you will need to delete old version from the repo", what does this mean? Does it mean I need delete the `terraform.yaml` you generated?
