### ISSUE TITLE
Support for "datetime" type from swagger in api.yaml

### ISSUE THREAD

**Issue by zikalino** [Azure/magic-module-specs#18]
Currently there's no support for datetime.

**Comment by zikalino** [comment]
I assume this should be:
!ruby/object:Api::Azure::SDKTypeDefinition::ISO8601DateTimeObject
mentioned here:
Azure/autorest.devops#8
However when searching for "ISO8601DateTimeObject" in MM repo here:
https://github.com/VSChina/magic-modules/tree/azure_backend
I couldn't find any references.

**Comment by JunyiYi** [comment]
This is a new feature not added to MM yet.

**Comment by zikalino** [comment]
@JunyiYi does it mean MM will fail when it encounters this data type? Should we temporarily have string instead?

**Comment by JunyiYi** [comment]
@zikalino Yes MM will throw exception. And this is a TODO item for me. Why can't we just leave it there and wait until MM supports it later.

**Comment by JunyiYi** [comment]
MM supported the data types, templates will be added shortly.
