### ISSUE TITLE
Support for "timespan" in api.yaml

### ISSUE THREAD

**Issue by zikalino** [Azure/magic-module-specs#19]
Could we have some support for "timespan". Could be a placeholder type for now.

**Comment by zikalino** [comment]
I assume this should be:

!ruby/object:Api::Azure::SDKTypeDefinition::ISO8601DurationObject

mentioned here:

https://github.com/Azure/autorest.devops/issues/8

However when searching for "ISO8601DurationObject" in MM repo here:

https://github.com/VSChina/magic-modules/tree/azure_backend

I couldn't find any references.

**Comment by JunyiYi** [comment]
This is a new feature not added to MM yet.

**Comment by JunyiYi** [comment]
MM supported this type, code templates will be completed shortly.
