### ISSUE TITLE
Equivalent of Azure::SDKTypeDefinition::ComplexArrayObject in Module UX definition

### ISSUE THREAD

**Issue by zikalino** [Azure/magic-module-specs#22]
Needs some clarification in the spec.
How to properly map:

!ruby/object:Api::Azure::SDKTypeDefinition::ComplexArrayObject: an array of structures value in SDK.

into module us:

Some combination of:

!ruby/object:Api::Type::Array
!ruby/object:Api::Type::NestedObject

or should be just !ruby/object:Api::Type::Array with **properties**?

**Comment by zikalino** [comment]
I would also like to understand how E2E implementation of complex arrays works.
I found only one reference here:

https://github.com/VSChina/magic-modules/blob/f3d188fa4d468bfd3aac14bd7bc081ff8da53de5/api/azure/sdk_type_definition.rb#L78

But no other references anywhere else, so it seems to me that adding it to **api.yaml** file has no effect

**Comment by JunyiYi** [comment]
This would be a feature request for now.

**Comment by zikalino** [comment]
I found some information in the new documentation and created this issue here:

https://github.com/Azure/autorest.devops/issues/11

Pls check if this is going to be correct approach.
Is this feature already working correctly?

**Comment by JunyiYi** [comment]
@zikalino It is already defined in the original MM (take an example here: https://github.com/VSChina/magic-modules/blob/master/products/compute/api.yaml#L295-L399). The feature request here means I am not sure whether it is supported in Azure or not (very probably not). But if you need to do so, just use the example above.

**Comment by zikalino** [comment]
@JunyiYi  It seems to be used in this api.yaml file (is this file correct?):

https://github.com/VSChina/magic-modules/blob/azure_backend/products/azfrontdoorbackendpool/api.yaml

and Terraform module generated here:

https://github.com/VSChina/magic-modules/blob/azure_backend/build/azterraform/azurerm/resource_arm_front_door_backend_pool.go

So does it already work for Terraform? Was that module tested?

I am a bit worried it may not work for Ansible yet, as ComplexArrayObject was introduced here:

https://github.com/VSChina/magic-modules/commit/e8bb61e42d8f474be61b0fb2628e4cb142c2956d

and it seems there were several changes in the same PR, but related only to Terraform.

**Comment by JunyiYi** [comment]
@zikalino You are correct. I have tuned the code for Terraform, Ansible support is unknown to me. We need to check the generated code to see whether it is supported or not.

**Comment by zikalino** [comment]
"does not need a lot marshaling/unmarshaling since its module_args_spec shares the similar structure as Python SDK." -- this is not necessarily correct, the structure of subelements may be different than SDK, there may be cases when it's flattened or elements are renamed too.

**Comment by JunyiYi** [comment]
Provide examples in the spec: #59.
