### ISSUE TITLE
Generated FrontDoor implementation doesn't preserve existing state of resource

### ISSUE THREAD

**Issue by zikalino** [Azure/magic-module-specs#33]
I checked file generated for Terraform here:

https://github.com/VSChina/magic-modules/blob/azure_backend/build/azterraform/azurerm/resource_arm_front_door.go

It seems like **resource_arm_front_door** doesn't include definition of subresources.

If I understand correctly, if this implementation is applied on existing Front Door instance that has existing subresources, they will be removed when CreateOrUpdate function is called.

I think this is not correct behavior.

**Comment by JunyiYi** [comment]
This is the wrong one, ignore it.
