### ISSUE TITLE
Proposed simplification of api.yaml specification - variable names

### ISSUE THREAD

**Issue by zikalino** [Azure/magic-module-specs#35]
Currently we have two parameters:
- go_variable_name
- python_variable_name

In case of Ansible modules this variable name is module's internal.
Therefore the name can be anything, and it could be easily derived from **python_parameter_name**.

Another question is why there's no equivalent **go_parameter_name**?

https://github.com/Azure/magic-module-specs/blob/28df4845358ba0f49c94d2562129c5bf691ba7fb/azurefirewall/api.yaml#L32

```
            id_portion: azureFirewalls
            go_variable_name: name
            python_parameter_name: azure_firewall_name
            python_variable_name: name
```

**Comment by JunyiYi** [comment]
Since it is generated, we will just let it be there so the user could control more about the generated source code. Go does not need to specify parameter name when calling functions (just like C).

**Comment by JunyiYi** [comment]
For `go_parameter_name`, because we do not need to specify parameter when calling method in Go.

For example, in Python, we do:
```python
client.create(resource_group_name = rgname, name = name)
```

But in Go, we only do:
```go
client.Create(rgname, name)
```
