### ISSUE TITLE
api.yaml doc should have more info on SDK references

### ISSUE THREAD

**Issue by zikalino** [Azure/magic-module-specs#36]
According to the doc, for instance:

"The hash table key resourceGroupName could be actually any string, but we commend to use something make sense. "

This means that the names of the keys in azure_sdk_definition can be anything.
However in the same time we usually use the exact path in in the parameters/properties.

I'm not what's is MM's algorithm to derive actual dependencies.

For instance, let's say that in SDK we have following structure:
**properties/xxx/something**, which is flattened to **properties/something** in the module UX.

SDK definition will have following keys:

(1) **properties**
(2) **properties/xxx**
(3) **properties/xxx/something**

but the module UX will only refer (1) and (3) as module UX doesn't know about (2).
SDK definition doesn't really define structure, unless we derive that structure from **key** names, which is not specifically stated in the specification.

How MM knows that (2) should go in between (1) and (3). If we treat keys just as keys of hashtable without specific meaning, I can't see any way of deriving this information from existing structure.

**Comment by JunyiYi** [comment]
The keys are arbitrary, but not for the flattened strings. The document mentioned about the flattened keys: https://github.com/Azure/magic-module-specs/blob/master/RESOURCE_SPEC.md#sdk-operation-request, in this example, `A` `B` `C` `D` `E` could be any strings, but the flattened string `B/C/D` must match the keys defined above.

**Comment by JunyiYi** [comment]
Updated documentation here #59.
