### ISSUE TITLE
Discussion: Proposal of splitting api.yaml file or....

### ISSUE THREAD

**Issue by zikalino** [Azure/magic-module-specs#37]
Initial promise of Magic Modules was generating Ansible and Terraform modules from a single definition file.

After analyzing **api.yaml** files, for instance, there's probably only around 30% of code that is common between **Ansible/Python** and **Terraform/Go**. For instance:

https://github.com/Azure/magic-module-specs/blob/master/azurefirewall/api.yaml

In that common 30% (UX Definition) names of the properties and enum values follow Terraform convention (camel case) and are later converted to Ansible convention (python case).

Considering this it would be much cleaner to have separate **api-ansible.yaml** and **api-terraform.yaml** files.

### Redesign **api.yaml** to minimize split between Ansible and Terraform

It would require adjusting the mapping between UX and SDK, could be difficult to implement and we would still end up with some amount of differences.

### Use REST API directly from autogenerated modules**

An example could be found here: https://github.com/audevbot/autorest.devops.debug/blob/master/generated/intermediate/ansible-module-rest/azure_rm_azurefirewall.py

If we use Azure REST API directly from both Ansible and Terraform we could completely skip SDK dependency and the diversion we see would completely disappear.

In general advantages are:
- **api.yaml** file would become 100% generic for both Ansible/Terraform
- code generation would be simplified, as we wouldn't have to care about SDK implementation details which can lead to a lot of errors
- minimal dependencies to SDK

**Comment by JunyiYi** [comment]
Not a priority. This requires very large effort and needs to align with Google.
