### ISSUE TITLE
Weird Magic Modules error

### ISSUE THREAD

**Issue by zikalino** [Azure/magic-module-specs#68]
bundler: failed to load command: compiler (compiler)
Psych::DisallowedClass: Tried to load unspecified class: Provider::ResourceOverrides
  /usr/lib/ruby/2.6.0/psych/class_loader.rb:97:in `find'
  /usr/lib/ruby/2.6.0/psych/class_loader.rb:28:in `load'
  /usr/lib/ruby/2.6.0/psych/visitors/to_ruby.rb:391:in `resolve_class'
  /usr/lib/ruby/2.6.0/psych/visitors/to_ruby.rb:208:in `visit_Psych_Nodes_Mapping'
  /usr/lib/ruby/2.6.0/psych/visitors/visitor.rb:16:in `visit'
  /usr/lib/ruby/2.6.0/psych/visitors/visitor.rb:6:in `accept'
  /usr/lib/ruby/2.6.0/psych/visitors/to_ruby.rb:32:in `accept'
  /usr/lib/ruby/2.6.0/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
  /usr/lib/ruby/2.6.0/psych/visitors/to_ruby.rb:336:in `each'
  /usr/lib/ruby/2.6.0/psych/visitors/to_ruby.rb:336:in `each_slice'
  /usr/lib/ruby/2.6.0/psych/visitors/to_ruby.rb:336:in `revive_hash'
  /usr/lib/ruby/2.6.0/psych/visitors/to_ruby.rb:374:in `revive'
  /usr/lib/ruby/2.6.0/psych/visitors/to_ruby.rb:208:in `visit_Psych_Nodes_Mapping'
  /usr/lib/ruby/2.6.0/psych/visitors/visitor.rb:16:in `visit'
  /usr/lib/ruby/2.6.0/psych/visitors/visitor.rb:6:in `accept'
  /usr/lib/ruby/2.6.0/psych/visitors/to_ruby.rb:32:in `accept'
  /usr/lib/ruby/2.6.0/psych/visitors/to_ruby.rb:311:in `visit_Psych_Nodes_Document'
  /usr/lib/ruby/2.6.0/psych/visitors/visitor.rb:16:in `visit'
  /usr/lib/ruby/2.6.0/psych/visitors/visitor.rb:6:in `accept'
  /usr/lib/ruby/2.6.0/psych/visitors/to_ruby.rb:32:in `accept'
  /usr/lib/ruby/2.6.0/psych.rb:360:in `safe_load'
  /magic-modules/google/yaml_validator.rb:27:in `parse'
  /magic-modules/provider/config.rb:57:in `parse'
  compiler:129:in `block in <top (required)>'
  compiler:102:in `each'
  compiler:102:in `<top (required)>'

**Comment by JunyiYi** [comment]
From the error message `Psych::DisallowedClass: Tried to load unspecified class: `**`Provider::ResourceOverrides`**, we know that `Provider::ResourceOverrides` is not a valid ruby class (because GCP renamed it to `Overrides::ResourceOverrides`).

**Comment by JunyiYi** [comment]
I checked the code samples for ansible and terraform are correct, please take a look: https://github.com/Azure/magic-module-specs/blob/master/RESOURCE_SPEC.md#ansible-overrides-ansibleyaml.
