### ISSUE TITLE
Magic Modules reports following error

### ISSUE THREAD

**Issue by zikalino** [Azure/magic-module-specs#69]
According to the specification: "Note that all properties illustrated here are optional, which means you do not want to override anything in api.yaml"

This applies to 2 fields: "overrides" and "version_added"

D, [2019-07-05T08:00:18.613182 #6] DEBUG -- : Checking 'overrides' on <Provider::Azure::Ansible::Config>
bundler: failed to load command: compiler (compiler)
RuntimeError:  > Missing 'author'
  /magic-modules/google/yaml_validator.rb:66:in `check'
  /magic-modules/provider/azure/ansible/config.rb:25:in `validate'
  /magic-modules/provider/config.rb:65:in `parse'
  compiler:129:in `block in <top (required)>'
  compiler:102:in `each'
  compiler:102:in `<top (required)>'

**Comment by JunyiYi** [comment]
It is my fault not describing it clearly. Actually I mean the properties in `overrides` and `datasources` sections are completely optional. (But `overrides` itself is also required)

**Comment by JunyiYi** [comment]
Docs updated in #71 .
