### ISSUE TITLE
The api.yaml spec doesn't include list / list_by_something_else

### ISSUE THREAD

**Issue by zikalino** [Azure/magic-module-specs#7]
Azure rest API may provide more "list" functions.
There's simple "list" that lists resources in the resource group or can be list_by_something else
for instance subresources, like subnet can be "read" or listed by virtual network.
so i think we shoudl initially have support for these 2.

**Comment by zikalino** [comment]
Actually I think we already need things like "list" already that would list all the resources in subscription or in case of subresource like subnet "list" will list all the subnets in the virtual network and "read" will get particular subnet.

**Comment by JunyiYi** [comment]
More `list`s added to the spec: https://github.com/Azure/magic-module-specs/blob/master/RESOURCE_SPEC.md#sdk-operation-definition.
